name: adventcalendar2023_flutter2_14
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  gap: ^3.0.1
  go_router: ^12.1.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.4
  pedantic_mono: ^1.25.0

flutter:
  uses-material-design: true
